Implemented event for ChangingWarheadLeverStatusEventArgs
galaxy119/EXILED pull request #252
Opened 2020-09-16 15:06 UTC by gamehunt

ChangingWarheadLeverStatusEventArgs class didnt have corresponding event

2020-09-16 17:10 UTC, iRebbok requested changes

2020-09-16 17:10 UTC, iRebbok commented on Exiled.Events/Patches/Events/Player/ChangingWarheadLeverStatus.cs
> +    internal class ChangingWarheadLeverStatus
```suggestion
    internal static class ChangingWarheadLeverStatus
```
All patches must be in a static class

2020-09-16 17:21 UTC, gamehunt commented on Exiled.Events/Patches/Events/Player/ChangingWarheadLeverStatus.cs
> +    internal class ChangingWarheadLeverStatus
Fixed

2020-09-16 17:25 UTC, iRebbok approved these changes

2020-09-16 17:25 UTC, merged

2020-09-17 12:49 UTC, iRebbok commented
Forgot about the `Warhead` class, so I've moved it in https://github.com/galaxy119/EXILED/commit/591425aa6de6648e1f0c8c18ad752c6e750b4e9e commit