Documentation update
galaxy119/EXILED pull request #2680
Opened 2024-07-07 01:11 UTC by Banalny-Banan

Exiled documentation is often not very helpful in determining what properties/method actually do, and i want to fix this in order to make Exiled easier for beginners

2024-07-07 04:38 UTC, ALEXWARELLC commented
@NaoUnderscore

2024-07-08 16:52 UTC, Misfiy requested changes

2024-07-08 16:52 UTC, Misfiy commented on Exiled.Events/EventArgs/Map/ChangingIntoGrenadeEventArgs.cs
> +    /// Contains all information before a pickup grenade is changed into a live grenade.
Use ``<see cref="GrenadePickup"/>`` instead of ``pickup grenade``
Same for live grenade

2024-07-08 16:52 UTC, Misfiy commented on Exiled.Events/EventArgs/Map/ChangedIntoGrenadeEventArgs.cs
> +    /// Contains all information after a pickup grenade was changed into a live grenade.
Use <see cref="GrenadePickup"/> instead of pickup grenade
Same for live grenade

2024-07-08 16:53 UTC, Misfiy commented
> I want to continue rewriting/fixing documentation in other files, but can i get a little confirmation of whether this PR is needed at all, so i wont waste a lot of time on nothing in case there is a reason for not merging it?

Docs should be as clear as possible, feel free to continue

2024-07-12 19:59 UTC, NaoUnderscore requested changes

2024-07-12 19:59 UTC, NaoUnderscore commented on Exiled.CustomModules/API/Features/CustomItems/CustomItem.cs
> +        /// Gets the description. It can be is used in hints when the item is selected.
We don't use hints, we use `TextDisplay`. Fix spelling error as well.

2024-07-12 19:59 UTC, NaoUnderscore commented on Exiled.CustomModules/API/Features/CustomItems/CustomItem.cs
> +        /// Gets a <see cref="CustomItem"/> instance based on the specified custom item id.
I do personally find "Retrieve" more accurate, but that's just my opinion

2024-07-12 23:03 UTC, NaoUnderscore commented on Exiled.CustomModules/API/Features/CustomItems/CustomItem.cs
> +        /// Gets a <see cref="CustomItem"/> instance based on the specified custom item id.
👍🏼

2024-07-13 15:17 UTC, NaoUnderscore commented on Exiled.CustomModules/API/Features/CustomItems/CustomItem.cs
> +        /// Gets the description. It can be is used in hints when the item is selected.
Great 👍🏼

2025-04-01 16:42 UTC, closed without merging