[GH Repo] Fixed some stuff in the repository
galaxy119/EXILED pull request #2735
Opened 2024-07-19 19:56 UTC by skManux

**What changed?**

- Added logo and improved READMEs headers
- Deleted old documentation (Last commit was from 2 years ago)
- Fixed the "Localized READMEs" sections of all READMEs (Some did not have all the languages)
- Removed "Not Enabled" warning in the Analyzer Config
- Removed GettingStarted READMEs (Everything has been moved to the [website](https://exiled.to))
- Updated logos with the new ones (I downloaded them from the [website](https://exiled.to))
- Deleted other unused files

If possible, I would also like to get the _Exiled Contributor_ role on the Discord server. My username is _sk_manux_.

2024-07-19 23:14 UTC, xNexusACS approved these changes

2024-07-19 23:26 UTC, xNexusACS requested changes
DocFX is being used still, also useful in some cases

2024-07-20 11:31 UTC, skManux commented
> DocFX is being used still, also useful in some cases

I re-added the DoxFX configuration files. I re-added the Docusaurus docs too, because it seems that DocFX depends on the "docs" folder.

2024-07-20 11:37 UTC, Misfiy commented
no clue on any of this

2024-07-20 11:41 UTC, skManux commented
wdym?

2024-07-20 22:06 UTC, xNexusACS requested changes

2024-07-20 22:06 UTC, xNexusACS commented on assets/Exiled_Icon.ico
this file is used by the installer

2024-07-20 22:07 UTC, xNexusACS commented on assets/Exiled_Icon.ico
same for the jpg one

2024-07-21 16:20 UTC, skManux commented on assets/Exiled_Icon.ico
I re-added the images that you asked me

2024-07-21 20:44 UTC, xNexusACS submitted a review, later dismissed

2024-07-22 05:08 UTC, ALEXWARELLC commented
@xNexusACS As I suggest we hold back on this, and it's not that important, you can add the P3 label.

At some point, I'll write a bot to help me automate this process.

2024-07-22 06:27 UTC, xNexusACS commented
> @xNexusACS As I suggest we hold back on this, and it's not that important, you can add the P3 label.
> 
> At some point, I'll write a bot to help me automate this process.

sure

2024-07-24 00:14 UTC, ALEXWARELLC commented on Localization/README-BR.md
> +  </a>
For some reason, this will create underscores between the badges, + `![Image](URL)` is generally better for badges.

2024-08-09 12:44 UTC, ALEXWARELLC commented
@NaoUnderscore Squash merge

2024-08-23 03:18 UTC, NaoUnderscore commented
Fix conflicts

2024-08-23 04:18 UTC, xNexusACS approved these changes

2026-03-28 20:50 UTC, closed without merging