Added RoundStartingEventArgs
galaxy119/EXILED pull request #2797
Opened 2024-10-31 19:02 UTC by angelseraphim

Added an event that is called before OnRoundStarted and can disable the start of the round :P

2024-10-31 19:28 UTC, Marikider commented
😀

2024-10-31 19:30 UTC, angelseraphim commented
👋

пт, 1 нояб. 2024 г., 00:29 Mariki ***@***.***>:

> 😀
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Exiled-Team/EXILED/pull/2797#issuecomment-2450664130>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBTD2LQFUDFQJK7SQE3WLHLZ6KAIZAVCNFSM6AAAAABQ65632WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINJQGY3DIMJTGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-09 20:19 UTC, xNexusACS requested changes

2024-11-09 20:19 UTC, xNexusACS commented on Exiled.Events/EventArgs/Server/RoundStartingEventArgs.cs
> +    /// Contains nothing.
🤔, it does contain something.

2024-11-09 20:19 UTC, xNexusACS commented on Exiled.Events/EventArgs/Server/RoundStartingEventArgs.cs
> +        /// Gets or sets a value indicating whether the event can continue.
Gets or sets a value indicating whether the round can start or not.

2024-11-09 20:19 UTC, xNexusACS commented on Exiled.Events/Handlers/Server.cs
> +        /// Invoked before round will started.
Invoked before round starts.

2024-11-14 09:13 UTC, xNexusACS approved these changes

2024-11-15 10:42 UTC, xNexusACS requested changes

2024-11-15 10:42 UTC, xNexusACS commented on Exiled.Events/EventArgs/Server/RoundStartingEventArgs.cs
> +    /// Contains isallowed or not.
One last touch before merging.

Contains all information before the start of the round.

Everything should be documented correctly.

2024-11-17 06:40 UTC, xNexusACS approved these changes

2024-11-17 07:10 UTC, closed without merging