Development docs & API change
galaxy119/EXILED pull request #333
Opened 2020-12-02 23:25 UTC by Thundermaker300

* Doc stuff: as always
* Moving Player::GetCameraById to (static) Map::GetCameraById (having it as a non-static in the player class literally made no sense)
* Adding an overload to Player::SetCamera to take a camera object

2020-12-02 23:27 UTC, PintTheDragon requested changes
This should be added back with a deprecation notice. Any plugins using it will break.

2020-12-02 23:28 UTC, PintTheDragon commented
Wait I think I did it wrong fuck. It's the line where you remove the function from Player.

2020-12-02 23:29 UTC, PintTheDragon commented on Exiled.API/Features/Player.cs
> -        /// <summary>
This should be added back with a deprecation notice. Any plugins using it will break.

2020-12-02 23:30 UTC, PintTheDragon commented
I think I did it right this time.

2020-12-02 23:31 UTC, PintTheDragon commented
Wait I'm blind lmao you already did it

2020-12-02 23:31 UTC, PintTheDragon approved these changes
Yeah it's good

2020-12-03 00:35 UTC, Thundermaker300 commented
Thanks, Pint

2020-12-05 10:31 UTC, iRebbok approved these changes

2020-12-05 10:32 UTC, merged