Bunch of stuff related to cameras
galaxy119/EXILED pull request #346
Opened 2020-12-10 20:10 UTC by Thundermaker300

Looking for some feedback here
* Not sure about some of the enum docs
* The cameras have been stored as an array whereas everything else is lists, and it feels weird - I know Scp079PlayerScript provides all the cameras as an array, but I'm not sure how to go about changing it (if we even should).

2020-12-11 16:00 UTC, Thundermaker300 commented
@iRebbok Any advice for this?

2020-12-11 18:04 UTC, iRebbok commented
@Thundermaker300 Wdym changing the array in Scp079PlayerScript?

2020-12-11 18:06 UTC, iRebbok commented on Exiled.API/Enums/CameraType.cs
> +        // Light
Use regions instead, also disable the warning StyleCop gives about it

2020-12-11 18:19 UTC, Thundermaker300 commented
> Wdym changing the array in Scp079PlayerScript?
Not changing the array in the Scp079PlayerScript, but changing it from an array to a List<Camera079> in the actual Map class, so that it matches the rest of the API already existing.

2020-12-11 18:26 UTC, iRebbok commented
> Not changing the array in the Scp079PlayerScript, but changing it from an array to a List<Camera079> in the actual Map class, so that it matches the rest of the API already existing.

Yep, free fell to change it for API cleanliness

2020-12-11 18:33 UTC, Thundermaker300 commented
Should I depreciate the old API for the array or just change it to a list? If I do depreciate it, what should the new API be called? I'm honestly not sure if just replacing it would be a bad idea - I'm not sure many plugins use the array (and we could make an announcement telling people to expect the change)

2020-12-11 18:36 UTC, iRebbok commented
> Should I depreciate the old API for the array or just change it to a list? If I do depreciate it, what should the new API be called? I'm honestly not sure if just replacing it would be a bad idea - I'm not sure many plugins use the array (and we could make an announcement telling people to expect the change)

Go ahead and change it if the API hasn't been released as full release yet.

2020-12-11 18:37 UTC, Thundermaker300 commented
Nono, I mean the Map.Cameras API (Camera079[]), I think it's been here for quite a bit

2020-12-11 18:38 UTC, iRebbok commented on Exiled.API/Enums/CameraType.cs
> +#pragma warning disable SA1124 // Do not use regions
Move this line up after the namespace, as we do in event files 😏

2020-12-12 02:42 UTC, Thundermaker300 commented
Probably best to make this change, however you might want to announce that it's being changed w/o warning

2020-12-13 11:32 UTC, iRebbok requested changes

2020-12-13 11:32 UTC, iRebbok commented on Exiled.API/Extensions/CameraExtensions.cs
> +        public static ZoneType GetZone(this Camera079 camera) => GetRoom(camera).Zone;
The GetRoom method may return null, make it null safety

2020-12-14 06:43 UTC, iRebbok approved these changes

2020-12-14 06:44 UTC, merged