More 079 crap
galaxy119/EXILED pull request #353
Opened 2020-12-15 02:45 UTC by Thundermaker300

* `ElevatorTeleport` event: Invoked before Scp-079 switches floors using elevators. Event args take player, camera, ap amount, and isAllowed
* Adding `Map::GetCameraByType(CameraType)` - Returns a `Camera079` with the given CameraType

2020-12-15 02:59 UTC, Thundermaker300 commented
why is 079 so lame

2020-12-16 13:32 UTC, iRebbok requested changes

2020-12-16 13:32 UTC, iRebbok commented on Exiled.API/Features/Map.cs
> +        /// gets the camera with the given camera type.
Lowest case?

2020-12-16 13:32 UTC, iRebbok commented on Exiled.Events/Patches/Events/Scp079/Interacting.cs
> +                                break;
Too many code breakers

2020-12-16 13:32 UTC, iRebbok commented on Exiled.Events/Patches/Events/Scp079/Interacting.cs
> +                                    break;
Same, the one that at the end there is already enough

2020-12-19 13:13 UTC, iRebbok approved these changes

2020-12-19 13:13 UTC, merged