Added Map.ChangeUnitColor()
galaxy119/EXILED pull request #398
Opened 2021-02-07 12:39 UTC by Jesus-QC

Credits to sanyae

2021-02-07 13:35 UTC, iRebbok commented
Looks a little strange. What if a dev wants to change the color twice? Does it even have to be in the API?

2021-02-07 15:09 UTC, Jesus-QC commented
Well.. Amathor asked me to put this in here but you are right, I will have to check if the unit has already changed the color

2021-02-07 15:46 UTC, Jesus-QC commented
greeny green

2021-02-07 16:41 UTC, iRebbok commented
@galaxy119 Your move

2021-02-08 10:39 UTC, galaxy119 commented
Looks solid to me, this has been possible in the game for several versions (since MP1 iirc). I'm fairly confident this won't be something removed from the game.

2021-02-10 10:06 UTC, iRebbok requested changes

2021-02-10 10:06 UTC, iRebbok commented on Exiled.API/Features/Map.cs
> +                }
Simplify the regex to `<[^>]*?>` and call `Regex::Replace(string, string, string)` instead to remove tags (https://regex101.com/r/9Wsd6l/1)

2021-02-12 18:58 UTC, merged